//Source - https://stackoverflow.com/a/67620581
//Posted by Syed, modified by community. See post 'Timeline' for change history
//Retrieved 2026-06-06, License - CC BY-SA 4.0
//function randomYear() {
 //   return Math.round(Math.random() * (2199 - 1900) + 1900)
//}
    var splashes = Array( //got a lot of these suggested here https://x.com/N4pstr/status/2063457245342445639
        "It's tail time!",
        "As seen on Twitter!",
        "Also try Neocities!",
        "Try hovering over any asterisks you see!",
        "awawawawawawawa!",
        "It's Awesome baby!",
        "I miss GilvaSunner...",
        "FUCK ICE",
        "Trans Rights!",
        "Holla Holla Get Dollar!",
        "John Madden!",
        "Football!",
        "Sponsored by the Haltmann Works Company!",
        "Please for the love of god watch Shin Kamen Rider (2023)!",
        "Born to die, world is a FLAC!",
        "Follow @_38mb on twitter dot com!",
        "Sometimes, I dream about cheese...",
        "Foxes Love It!",
        "The kids are smoking coronavirus!",
        "He is red for an AMAZING reason!",
        "It's wii.gay dawg, it's lit",
        '"The primary aim of modern warfare (in accordance with the principles of doublethink...) is to use up the products of the machine without raising the general standard of living." -1984, George Orwell',
        "This is not a joke, I genuinely wholeheartedly believe the Among Us cartoon (2026) is very good and you should watch it with some friends right now",
        "Please help, I'm still stuck in Vim...",
        "He is 20 years old!",
        "According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway because bees don't care what humans think is impossible. Yellow, black. Yellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Let's shake it up a little. Barry! Breakfast is ready! Coming! Hang on a second. Hello? - Barry? - Adam? - Can you believe this is happening? - I can't. I'll pick you up. Looking sharp. Use the stairs. Your father paid good money for those. Sorry. I'm excited. Here's the graduate. We're very proud of you, son. A perfect report card, all B's. Very proud. Ma! I got a thing going here. - You got lint on your fuzz. - Ow! That's me! - Wave to us! We'll be in row 118,000. - Bye! Barry, I told you, stop flying in the house! - Hey, Adam. - Hey, Barry. - Is that fuzz gel? - A little. Special day, graduation. Never thought I'd make it. Three days grade school, three days high school. Those were awkward. Three days college. I'm glad I took a day and hitchhiked around the hive. You did come back different. - Hi, Barry. - Artie, growing a mustache? Looks good. - Hear about Frankie? - Yeah. - You going to the funeral? - No, I'm not going. Everybody knows, sting someone, you die. Don't waste it on a squirrel. Such a hothead. I guess he could have just gotten out of the way. I love this incorporating an amusement park into our day. That's why we don't need vacations. Boy, quite a bit of pomp... under the circumstances. - Well, Adam, today we are men. - We are! - Bee-men. - Amen! Hallelujah! Students, faculty, distinguished bees, please welcome Dean Buzzwell. Welcome, New Hive City graduating class of... ...9:15. That concludes our ceremonies. And begins your career at Honex Industries! Will we pick our job today? I heard it's just orientation. Heads up! Here we go. Keep your hands and antennas inside the tram at all times. - Wonder what it'll be like? - A little scary. Welcome to Honex, a division of Honesco and a part of the Hexagon Group. This is it! Wow. Wow. We know that you, as a bee, have worked your whole life to get to the point where you can work for your whole life. Honey begins when our valiant Pollen Jocks bring the nectar to the hive. Our top-secret formula is automatically color-corrected, scent-adjusted and bubble-contoured into this soothing sweet syrup with its distinctive golden glow you know as... Honey! - That girl was hot. - She's my cousin! - She is? - Yes, we're all cousins. - Right. You're right. - At Honex, we constantly strive to improve every aspect of bee existence. These bees are stress-testing a new helmet technology. - What do you think he makes? - Not enough. Here we have our latest advancement, the Krelman. - What does that do? - Catches that little strand of honey that hangs after you pour it. Saves us millions. Can anyone work on the Krelman? Of course. Most bee jobs are small ones. But bees know that every small job, if it's done well, means a lot. But choose carefully because you'll stay in the job you pick for the rest of your life. The same job the rest of your life? I didn't know that. What's the difference? You'll be happy to know that bees, as a species, haven't had one day off- if you're reading this you either have a very large monitor, or are cheating",
        "Still can't get nginx to work!",
        "Powered by Caddy!",
        "+4 Mult!",
        "Fair and Balanced!",
        "Powered by gamer chairs!",
        "Find my pages!",
        "The sensation of your screen!",
        "Also try Half-Life 3!",
        "Also try Portal 3!",
        "Also try Team Fortress 3!",
        "Shoutsout the artist formerly known as Pikmin 4",
        "Grr!",
        "Whatever...",
        "Thanks for sharing!",
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "https://www.youtube.com/watch?v=HV8IxKtAlrA",
        "https://www.youtube.com/watch?v=ATaVS0HycYw",
        "https://www.youtube.com/watch?v=VmNB568Y3ak",
        "Yuri!",
        "Play Ghost Trick!",
        "Play Spelunky!",
        "Play Neon White!",
        "Don't forget to take your estrogen!",
        "Javascript can suck my dick!",
        "Remember to drink water!",
        "Yup, that's going in my cringe compilation",
        "You've tunged your last Sahur...",
        "WE CAN SEE YOU... and we love your hair!",
        "Hello me from the future!",
        "Escape your hometown by any means necessary!",
        "Dess knight truther since chapter 2!",
        "Say my name",
        "Yes, pun intended! (Don't look for it though...)",
        " How's pizza gonna get a job now?",
        "Take no more than two please!",
        "I've come to make an announcement!",
        "marshall4 - i get gender envy from shadow the hedgehog",
        "KFAD 3 when?",
        "The two hardest things in software are DNS and naming things",
        "It's not DNS | There's no way it's DNS | It was DNS",
        "Jarvis, pull up the image that depicts me as the chad, and them as the virgin.",
        "They called me the Drift Queen back in college",
        "Fish fear me! Women fear me! Men fear me! I am so fucking lonely...",
        "DELTARUNE TOMORROW",
        "I used unpaid human labor for these shitty jokes!",
        "FIX YOUR HEART OR DIE",
        "FUCK TRUMP",
        "We are Charlie Kirk!",
        "THIS MACHINE KILLS FASCISTS",
        "Drink more ovaltine!",
        "To avoid dying to enemies, just don't!",
        "Fun fact! Most frogs are not fully forklift certified!",
        "The narwhal bacons at midnight!",
        "I like your shoelaces!",
        "Shrimps? Bugs!",
        "Fun fact! This fact isn't very fun!",
        "Lemon",
        "Be gay, do crime!",
        "I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX. Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project. There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!",
        'On the highed way. Straight up "driving it". and by "it", haha, well. lets justr say. My live.',
        "in the strippeed club. straight up 'jorking it'. and by 'it', haha, well. let's justr say. My Peanits",
        " The first 'Walks into a bar' joke occured in the first recorded society (Sumer)!",
        " Imagine having your quote on this website!",
        "Less bugs than Hollow Knight!",
        "100% AI free!",
        "Mostly JS free!",
        "Now with one more atom!",
        "What's up doc?",
        "Approved by most horses!",
        "Approved by most houses!",
        "The secret third option!",
        "Now with real coconut!",
        "Have you seen the new show? It's on Tubu. It's literally on Heebee. It's on Poodee with ads. It's literally on Dippy. You can probably find it on Weeno. Dude it's on Gumpy. It's a Pheebo original. It's on Poob. You can watch it on Poob. You can go to Poob and watch it. Log onto Poob right now. Go to Poob. Dive into Poob. You can Poob it. It's on Poob. Poob has it for you. Poob has it for you",
        "Short one liner splash message!",
        "This is the Museum of Twitter, the show where we talk about the most important tweets in the history of Twitter dot com!",
        "The radical pro-transgenders are ruining america!",
        "Read Homestuck! It's really not that long, I promise!",
        "Why did the chicken cross the road? No like actually I need to know!",
        " Spread buttcheeks, not hate!",
        "Always remember to empty the lint trap!",
        "Your first commitment should ALWAYS be to the bit!",
        "Mom look, I'm a splash text!",
        'All animals are equal, but some animals are more equal than others" -Jorjor Well, 1987',
        "Play Secret Little Haven!",
        "When that home brew hits!",
        "Updated autopsy report!",
        "You have lost the game!",
        "I turned myself into a splash text Morty! I'm Splash Text Rick!",
        "As seen on Ellen!",
        "1/8192!",
        "Full Odds!",
        "The wild Ho-Oh used Struggle!",
        "I haven't actually played pokemon!",
        "Now including woke!",
        "Now with vitimin C!",
        "I need more computers!",
        "I'm not taking my sneakers off!",
        "I don't even go here!",
        "The employees get to dance joyfully for 2 minutes every day!",
        "John Pork is calling! Pig up the phone!",
        "Go to your locals!",
        "They made our frogs gay </3",
        "Unexpected item in bagging area!",
        "It's not just a web— it's a site",
        "Insurance fraud committed daily!",
        "Listen to Vylet Pony!",
        "Shit, clicked the wrong tab!",
        "I hardly know her!",
        "What would it even mean to frog a woman?",
        "Hello everybody my name is Welcome!",
        "Arch BTW!",
        "The next splash is true!",
        "The previous splash is false!",
        "Download Dolphin emulator today!",
        "Counting or not counting self hosting?",
        "Is that the guy from Fortnite?",
        "Watch Nirvanna The Band The Show The Movie!",
        "Did you see the news today?",
        "Powered by hamsters in wheels!",
        "TAke a look, yall: IMG_4346.jpeg",
        "Check out Meta Runner!",
        "This is what happens when you don't know how to code!")
    var splash = splashes[Math.floor(Math.random()*splashes.length)];

    var dictionary;
    function start(){dictionary=splash;
    return dictionary;
}
//you use start output to render innerhtml
// you dont do another document.get because lower is not a dom element its is Js object and we have used start return to make is consumable
// == is comparative = is used as setter we are setting not comparing as code would suggest 
document.getElementById("A100").innerHTML=start();